constants:   # 커스텀 속성
  jwt:
    issuer: green502@green.com # JWT 토큰 발행자 정보
    bearer-format: JWT
    claim-key: signedUser
    secret-key: DeaguGreenArtAcademyClass502MsaClassFighting # 비밀 레시피(절대 공개되어서는 안 된다)
    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 5 # 15분
    access-token-validity-milliseconds: 5_000 # 15분
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue
    refresh-token-cookie-validity-seconds: 1_296_000 # 15일
    refresh-token-validity-milliseconds: 1_296_000_000 # 15일
  file:
    directory: D:/test/download/greengram

spring:
  application:
    name: greengramjpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greengram_jpa
    username: root
    password: green502
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update # create, update, none,   (DDL: 데이터 정의어 - CREATE, ALTER, DROP)
    properties:
      hibernate:
        jdbc:
          batch_size: 50 # 배치작업 크기 설정
        format_sql: true # 쿼리문 보기편하게 포맷팅
        order_updates: true # JPA Batch 작업 활성화
    show-sql: true # JPA가 쿼리문 로그에 출력

mybatis: # Mybatis 세팅
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml # xml 파일 위치